version: '3.4'

services:
  projectmanager:
    image: projectmanager
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - shared_network
    environment:
      DB_USER: AJL420
      DB_PASSWORD: comme
      DB_NAME: project_man
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 1024mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: AJL420
      POSTGRES_PASSWORD: comme
      POSTGRES_DB: project_man
    networks:
      - shared_network

networks:
  shared_network: